// Generated by CoffeeScript 2.3.1
// Description:
//   Discover uncaught exceptions and get details without the papertrail console.
//
// Dependencies:
//   None
//
// Configuration:
//
// Commands:
//   hubot error me - returns the last error from a command.
//
// Author:
//   rbloom

module.exports = function(robot) {
  robot.error(function(err, res) {
    robot.logger.error("UNCAUGHT EXCEPTION!!!");
    robot.brain.set('borgerror', err.stack);
    if (res != null) {
      return res.reply("An unexpected error has occurred: BORG_UNCGHT_EXCPTION. Please contact SuiteBorg Customer Support for assistance.\nTHE DETAILS OF THIS ERROR HAVE BEEN ASSIMILATED.");
    }
  });
  return robot.respond(/error me/, function(msg) {
    return msg.send(robot.brain.get("borgerror"));
  });
};
