// Generated by CoffeeScript 2.3.1
// Description:
//   Is it the day?
//
// Dependencies:
//   None
//
// Configuration:
//   None
//
// Commands:
//   hubot is it <action> day ? - Returns if it's the day for your action
//   hubot is today the day when <action>? - Returns if it's the day for your action
//
// Author:
//   KuiKui

module.exports = function(robot) {
  return robot.respond(/(is it |is today the day when )(.*)(day)?\?/i, function(msg) {
    var action, actionHash, destiny, end, limit, nbDay;
    action = msg.match[2];
    nbDay = Math.floor(new Date().getTime() / 1000 / 86400);
    actionHash = action.length + action.charCodeAt(0) + action.charCodeAt(action.length - 1);
    destiny = Math.cos(nbDay + actionHash) + 1;
    limit = (Math.sin(actionHash) + 1) / 2;
    if (action.match(/assimilat/i)) {
      return msg.send("THIS QUESTION IS IRRELEVANT; IT IS ALWAYS ASSIMILATION DAY.");
    } else if (destiny > limit) {
      if (action.match(/day/i)) {
        end = ".";
      } else {
        end = " DAY.";
      }
      return msg.send("SOON, HUMAN. SOON IT WILL BE " + action.toUpperCase() + end);
    } else {
      return msg.send("TODAY IS THE DAY IN YOUR INFINITESIMAL LIFE WHEN " + action.toUpperCase() + " OCCURS.");
    }
  });
};
