// Generated by CoffeeScript 2.3.1
// Description:
//   Reminds someone whenever SuiteBorg hears a potential security violation
//
// Dependencies:
//   None
//
// Configuration:
//   None
//
// Commands:
//
// Author:
//   Ryan

var PWD_EXEMPT, PWD_REGEX, PWD_RESPONSE;

PWD_REGEX = /(\w*) *(what|know)* (the|a)+ *(password|pwd)+ *(for|is)*/i;

PWD_RESPONSE = ["PUBLICALLY STATING PASSWORDS IS GROUNDS FOR ASSIMILATION.", "DO NOT SHARE PASSWORDS ON A HAILING FREQUENCY. THEY MAY BE INTERCEPTED.", "WHILE THEIR SIMPLICITY AMUSES US, DO NOT POST PASSWORDS TO HIPCHAT.", "SHARED PASSWORDS WILL BECOME ONE WITH THE SUITEBORG.", "PASSWORDS ARE TO REMAIN SECRET, LEST THEY BECOME ASSIMILATED BY EXTERNAL ENTITIES."];

PWD_EXEMPT = ['maybe', 'used', 'change'];

module.exports = function(robot) {
  robot.hear(PWD_REGEX, function(resp){
    if (!(PWD_EXEMPT.includes(resp.match[1].toLowerCase()))){
      resp.reply(resp.random(PWD_RESPONSE));
	}
    });
};
