// Generated by CoffeeScript 2.3.1
// Description:
//   Create a new Pointing Poker session
//
// Dependencies:
//   None
//
// Configuration:
//   None
//
// Commands:
//   hubot planning/pointing poker - Creates a new planning poker session for you.
//
// Author:
//   Ryan

module.exports = function(robot) {
  return robot.respond(/(planning|pointing) poker/i, function(msg) {
    return msg.http("https://www.pointingpoker.com/Home/StartOrJoinSession").get()(function(err, res, body) {
      var e, regex, sessionID;
      if (err) {
        console.log(JSON.stringify(err));
        msg.send("WE WERE UNABLE TO GET A SESSION.");
        return;
      }
      try {
        regex = /"\/(\d*)"/g;
        sessionID = regex.exec(body);
        return msg.send("https://www.pointingpoker.com/" + sessionID[1]);
      } catch (error) {
        e = error;
        msg.send("WE WERE UNABLE TO ASSIMILATE THE SESSION.");
        return console.log(JSON.stringify(e));
      }
    });
  });
};
