// Generated by CoffeeScript 2.3.1
// Description:
// Make a slogan using sloganizer.net
//
// Dependencies:
// None
//
// Configuration:
// None
//
// Commands:
// hubot slogan <thing> - Temporarily assimilate a marketing firm
//
// Author:
// DafyddCrosby

var getSlogan;

getSlogan = function(msg, query) {
  return msg.http(`http://www.sloganizer.net/en/outbound.php?slogan=${query}`).get()(function(err, res, body) {
    var slogan;
    slogan = body.replace(/<.*?>/g, "");
    if (!err) {
      return msg.send(slogan.toUpperCase());
    }
  });
};

module.exports = function(robot) {
  return robot.respond(/slogan (.*)/i, function(msg) {
    return getSlogan(msg, msg.match[1]);
  });
};
