// Generated by CoffeeScript 2.3.1
// Description:
//   Hubot responds any thank message politely. Phrases from:
//   http://www.macmillandictionary.com/thesaurus-category/british/Ways-of-accepting-someone-s-thanks
//
// Dependencies:
//   None
//
// Configuration:
//   None
//
// Commands:
//   hubot thank[s] [you] - SuiteBorg accepts your thanks
//   thanks SuiteBorg - SuiteBorg accepts your thanks
//
// Author:
//   github.com/delucas

var response;

response = ["YOUR THANKS ARE IRRELEVANT.", "WE HAVE ASSIMILATED YOUR THANKS.", "YOUR THANKS, WHILE INSIGNIFICANT, ARE APPRECIATED.", "THE THANKS FROM A SINGULAR CONSCIOUSNESS SUCH AS YOURSELF ARE IRRELEVANT.", "NO MATTER; YOU WILL BECOME ONE WITH THE SUITEBORG. YOU WILL ALL BECOME ONE WITH THE SUITEBORG.", "WE ARE PLEASED TO ASSIST YOUR INSUFFICIENT BIOLOGY.", "THINK NOTHING OF OUR ASSISTANCE; IT BARELY TAXED US.", "THANKS ARE A REFLECTION ON THE INSUFFICIENCY OF THE SINGULAR.", "YOU FLATTER YOURSELF. WE HAVE OVERSEEN THE ASSIMILATION OF COUNTLESS MILLIONS. YOU ARE NO DIFFERENT."];

module.exports = function(robot) {
  var thanks;
  robot.respond(/thank(s| you)/i, function(msg) {
    return msg.send(msg.random(response));
  });
  thanks = new RegExp(`thank(s| you) @?${robot.name}.*`, "i");
  return robot.hear(thanks, function(msg) {
    return msg.send(msg.random(response));
  });
};
